* Principles
** Introduction
   List of principles (source: miscellany) to imbibe

** Principles

*** Logic, reason and common sense must trump everything else in decision-making

    While logic drives decisions, recognize that feelings and emotions are very relevant as well and must be given room for expression in the process.

*** Optimize for the long term

    Put a lot of emphasis on thinking about the long term effects of the decisions you make. Keep the future of the mission in mind while thinking about major decisions. Think about second- and third-order consequences of the decisions you make.

*** Know what the 20 is in the 80/20 rule

    Efficiency is key. Distinguish what’s important from what’s not and deal with the important things first.

*** Know how to deal with not knowing

    Not knowing can be uncomfortable. Embrace the discomfort and understand that the ability to deal with not knowing is more powerful than knowing. Your goal is to come up with the best answer, the probability of your having it immediately is very small and that even once you have it, you need to test it with other people to be confident about it.

*** It is okay to make mistakes but unacceptable to not learn from them

    Do not feel bad about your mistakes and those of others. Love them! Learn from them and share the lessons. When you make mistakes remember to reflect and never worry about looking good - worry about achieving the goals.

*** Be aware of cognitive biases and learn to avoid them.

    Cognitive biases are natural tendencies to think in certain ways that can lead to systematic deviations from rationality and good judgment. They are responsible for a huge class of judgement errors. This blindness can be extremely harmful. Since you are an integral part of the company, your blindness is the company’s blindness.

    The key thing to understand about them is that they’re completely invisible to the person falling prey to them. So, you have to put in a lot of extra effort in order to understand them and systematically avoid them. One of the best ways is to ask people around you for opinion before making a decision.

*** Be assertive and open minded

    Recognize that you always have the right to have and ask questions. Have strong opinions, because having a wrong opinion is better than having no opinion.

*** Be extremely open and transparent

    Be radically transparent when it comes to your work both within and outside your circles. Have integrity and demand it from others. Never say anything about a person you wouldn’t say to them directly.

*** Recognize that people are built very differently

    Understand and empathize with each person who works with you so that you know what to expect from them. Think about their very different personal values, abilities and priorities. Don’t try to hide these differences. Explore them openly to figure out what work is the best fit for the person.
